locale: "en"

variableGroups:
  - title: "Instance Settings"
    variables:
      - ${ad_index}
  - title: "Access"
    variables:
      - ${ssh_public_key}

variables:
  ad_index:
    type: integer
    required: true
    title: Availability Domain
    description: "Choose the AD to place the VM. Use 0 = AD-1, 1 = AD-2, 2 = AD-3. Tip: if AD-1 is out of capacity, try AD-2 or AD-3."
    default: 0
    minimum: 0
    maximum: 2
    multipleOf: 1

  ssh_public_key:
    type: oci:core:ssh:publickey
    required: true
    title: SSH Public Key
    description: >
      Paste your SSH public key to access the VM via SSH.
      On macOS/Linux: run `cat ~/.ssh/id_ed25519.pub` (or `cat ~/.ssh/id_rsa.pub`).
      On Windows (PowerShell): run `type $env:USERPROFILE\.ssh\id_ed25519.pub`.
      If you don't have a key yet, generate one with `ssh-keygen -t ed25519`.
